### ISSUE TITLE
Collisions of Ids

### ISSUE THREAD

**Issue by codematrix** [phatboyg/NewId#15]
Hi guys,

I know the Flake ago produces nice looking sequential GUIDs. However, this implementation of the library has the following fatal flaws.

When generating 5M GUIDs using parallel tasks here are the issues:

- It roughly takes 5 seconds to generate 5M GUIDs. This rather slow considering other libraries can produce 5M GUIDs in less than 300ms

- The issue is collisions. After running 5M GUIDs, we detected on average, the same GUID repeated between 70-300 times per run. This is a big concern. I suggest not to use the Flake algo of GUIDs but rather just replace the last 8 bytes of the GUID to use an Unix Epoch Timestamp in milliseconds. Granted the timestamp portion of the GUID can have collisions but due to the fact the remaining part of a natural GUID (minus the last 8 bytes) provides a much better quasi-uniqueness than the Flake algo.

Hope this helps,

codematrix

**Comment by phatboyg** [comment]
If it doesn't work for your use case, don't use it.

The goal was not just unique, but ordered identifiers.

**Comment by codematrix** [comment]
Hi @phatboyg,

I'm only stating that fact that GUIDs should guarantee uniqueness. Order and sequence can still be maintained with a high degree of quasi-uniqueness using a different and much faster technique. This is not just in my case, this is everyone's best interest. GUIDs have the assumption of being unique.

You just mentioned that:

> The goal was not just unique, but ordered identifiers.

The order part your is maintained, but the most important part is uniqueness, which is not guaranteed with your current implementation. I think you should mention this limitation in your docs. Users of this library may not be aware of this.

Anyways, I'll close this issue.

**Comment by phatboyg** [comment]
That's just it though, they _are_ unique. If you are seeing a case where they aren't, I'd like to know about it.

And I'm going to add a method to create multiple ids in a single call, which basically cuts the time down significantly to generate 1,000,000 identifiers. So if you ask for 10, you can get 10. Or maybe I can keep an internal buffer and just allocate them more quickly. Maybe. Hmm.

**Comment by codematrix** [comment]
Hi @phatboyg,

Here's the code sample that was used to show collisions.

        static void Main(string[] args)
        {
            var c1 = new ConcurrentBag<Guid>();

            Parallel.For(0, 5000000, (i) =>
            {
                c1.Add(NewId.NextGuid());
            });

            var groups = c1.GroupBy(g => g).Where(x => x.Count() != 1).ToList();
            var maxGrouping = groups.Max(x => x.Count());
            
            Console.WriteLine($"Collisions: {groups.Count()}");
            Console.WriteLine($"MaxGroupCollisions: {maxGrouping}");
        }

I know in most cases GUIDs will be generated on different PODs and threads. However, in our case, we have a conversation queue that can only be read by a single service. We can experience anywhere between 450K - 800K messages a daily that need to be logged using unique sequential GUIDs.

Hope this help,

codematrix

**Comment by phatboyg** [comment]
800k messages a day is nothing, as you said about, you can generate 5 million ids in about 300 milliseconds. And using your exact code, I didn't get a single duplicate in my test, so...

Well, not exact, I used an array (Guid[]) and use `result[i]` to store the results, instead of adding them to a bag (much slower).

**Comment by phatboyg** [comment]
There is a develop package that has a ton of tweaks in it if you want to test it out.

**Comment by codematrix** [comment]
Sure thing, will do. I'll provide some feedback - it might take a couple days. Just got swamp with a new RFP hence why I didn't respond to the last reply.

**Comment by phatboyg** [comment]
No worries, I've tweaked performance and moved to a SpinLock, as well as making it possible to ask for a block of ids as an array, to allocate 100's of them at once, versus one call at a time.
