### ISSUE TITLE
Ambiguous reference in projects that have transitive dependencies on both MassTransit.Abstractions and NewId

### ISSUE THREAD

**Issue by smarts** [phatboyg/NewId#22]
In projects that have dependencies on both MassTransit.Abstractions and NewId, the compiler has no way to tell the difference between usages because the class names and namespaces are identical.
@phatboyg have you considered making a breaking change and choosing a new namespace for this standalone library/package?

Edit: I'm aware that having both dependencies is a no-no if you can avoid it, but given that they could be transitive dependencies via NuGet, there are scenarios for which it cannot easily be avoided.

**Comment by phatboyg** [comment]
This was intentional to prevent two separate packages using the same algorithm from generating the same identifiers. While I can understand the transitive package issue, a better option might be an empty NewId package – but I don't think that would work either.

**Comment by smarts** [comment]
Yeah, sorry. I did not mean to be prescriptive about a solution. That was just the first one that came to mind.

**Comment by phatboyg** [comment]
Right, I get it. Eliminating the old package from your dependency chain would be the best course of action.

**Comment by UtopleMan** [comment]
Fantastic ID generator you guys have made here! Sorry if I'm being ignorant here, but wouldn't it be much easier to just keep it in it's own separate namespace, like "NewId" or..?

**Comment by phatboyg** [comment]
> Fantastic ID generator you guys have made here! Sorry if I'm being ignorant here, but wouldn't it be much easier to just keep it in it's own separate namespace, like "NewId" or..?

Long story, but NewId was originally _in_ MassTransit, later it was moved out to use it in other projects but the namespace remained the same to avoid breaking compatibility/builds. Now it's back in MassTransit.Abstractions (no namespace change required).

The problem with pushing a new v4 with the NewId namespace would be the duplication of the logic in the same process (people will screw up, they do it all the time and end up using both) resulting in duplicate Guids.

OH, and the whole static class with the same name as the namespace nonsense.
