### ISSUE TITLE
Get running on `dotnet` cli / .NET Core

### ISSUE THREAD

**Issue by dls314** [phatboyg/NewId#3]
Get NewId running on .net core.

**Comment by phatboyg** [comment]
Once .NET core is released, I'll do this for sure.

**Comment by jarroda** [comment]
@lahma Do you plan on submitting a PR for the work you have done porting this to .NET Core?

**Comment by jarroda** [comment]
Somehow I didn't notice the PR was already created for this.  I am working on porting MassTransit to Core so getting a compatible package for this on nuget.org is somewhat a blocker for that.  Anything I can help with on here @phatboyg ?

**Comment by phatboyg** [comment]
I should have some time to focus on getting this merged shortly. Today.

**Comment by phatboyg** [comment]
Ran into issues with the build script and NuGet.

**Comment by fubar-coder** [comment]
Any news about this feature?

**Comment by Charles89** [comment]
Can you give an update about this feature?

**Comment by phatboyg** [comment]
IF the pull request is updated to target both .NET 4.5.2 adn .NET standard 1 I'd be willing to accept it. As it is, I don't have the time to mess with all the broken stuff from project.json.

**Comment by wallymathieu** [comment]
I've added a new pull request for the issue #8

**Comment by wallymathieu** [comment]
Shouldn't this be fixed?

**Comment by phatboyg** [comment]
Yep. It's done.
