### ISSUE TITLE
Performance issue with NewId for Primary key

### ISSUE THREAD

**Issue by meysamhadeli** [phatboyg/NewId#30]
As in Doc mentioned, we have `sequential Id` with `NewID`. In the end, do we get generated sequential Id with ideal performance like `int` for cluster index?

**Comment by phatboyg** [comment]
NewId is designed for ordered insertion into `uniqueidentifier` primary keys that can be CLUSTERED. So yeah, in order is why NewId was designed, for use with SQL tables using UUID as the primary key.
