### ISSUE TITLE
Unique Id across all microservices

### ISSUE THREAD

**Issue by mehdihadeli** [phatboyg/NewId#31]
Hi,
Thanks for this useful package.
Could we create a unique ID across all services? Should we config each service instance separately to ensuring about uniqueness ?

**Comment by phatboyg** [comment]
Yes, it works across multiple services/servers/etc. 

There are [docs](https://masstransit.io/documentation/patterns/newid#newid).

**Comment by mehdihadeli** [comment]
Thanks, so, for using multi instance of a service in Kubernetes, it handles mac address based on each pod container? Or we should use a [processId](https://masstransit.io/documentation/patterns/newid#processid) here?

**Comment by phatboyg** [comment]
It's a combination of both, so yes use processId if you have multiple processes in the same pod.

**Comment by mehdihadeli** [comment]
Thanks
