### ISSUE TITLE
Question: are you aware of any ports or analogous implementations in java or php?

### ISSUE THREAD

**Issue by dbaggott** [phatboyg/NewId#32]
Hi, thank you for sharing your efforts with the community.

We're operating in a multi-language ecosystem with .NET, Java, and PHP and I was wondering if you happen to know of any ports of this to Java or PHP?

Thank you!

**Comment by phatboyg** [comment]
Actually, this might be a Java version of it:

https://github.com/phatboyg/MassTransit-CrossTown/tree/master/src/main/java/com/masstransitproject/crosstown/newid

**Comment by dbaggott** [comment]
In case it's helpful to someone else in the future.  This is NOT a port but does provide an orderable UUID in PHP Laravel: https://laravel.com/docs/10.x/helpers#method-str-ordered-uuid
