### ISSUE TITLE
How to use NewId in EF Core for Id / primary key columns

### ISSUE THREAD

**Issue by woha** [phatboyg/NewId#33]
I'm using EF Core 8 with Oracle 21c and all my entities have an `Id` column of type `Guid`.
How can I control / override the value generation for this column during an insert / `Add` to use NewId?

**Comment by phatboyg** [comment]
This is a question about how to use EF, and not an issue with `NewId`.

You can see how it is done in MassTransit, which sets the property before adding it and ensures the database layer never initializes the value:

https://github.com/MassTransit/MassTransit/blob/develop/src/Persistence/MassTransit.EntityFrameworkCoreIntegration/SagaClassMap.cs#L21

**Comment by woha** [comment]
Thank you for pointing me in the right direction, Chris!
