### ISSUE TITLE
NewId.NextGuid() vs NewId.NextSequentialGuid() usage

### ISSUE THREAD

**Issue by woha** [phatboyg/NewId#34]
What is the difference between `NewId.NextGuid()` and `NewId.NextSequentialGuid()`?
As I understood, `NewId.NextGuid()` generates sequential `Guid`s.

So my question is when to use which method?

**Comment by phatboyg** [comment]
MassTransit uses `NewId.NextGuid()` throughout. 

`NextSequentialGuid` is textually sorted in order, vs. the binary ordered needed by SQL Server.

**Comment by woha** [comment]
Thank you very much for the explanation!
